### ISSUE TITLE
Mazda HA integration is not longer loading.

### ISSUE THREAD

**Issue by Mr-Grover** [bdr99/pymazda#11]
Wasn't sure the best way to commutate so I hope this is okay. I was noticing the mazda app stopped working. I was able to delete and re add it but still no devices or components load and this error shows in the log 
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 65, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 37, in with_timeout
    return await task
  File "/usr/local/lib/python3.8/site-packages/pymazda/client.py", line 19, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
  File "/usr/local/lib/python3.8/site-packages/pymazda/controller.py", line 19, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 152, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 167, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 231, in __send_api_request
    raise MazdaException("Request failed for an unknown reason")
pymazda.exceptions.MazdaException: Request failed for an unknown reason
```

**Comment by bdr99** [comment]
Hi, thanks for reaching out. What version of HA are you using?

**Comment by Mr-Grover** [comment]
2021.5.5

**Comment by bdr99** [comment]
Can you try updating to 2021.6.0 or later and see if the log output is different? There are some changes in that version that might be able to give us more info in the logs when an error occurs.

**Comment by Mr-Grover** [comment]
I will update it this weekend and let you know. 

Thanks !

**Comment by pr0fetul** [comment]
Hi, I have the latest HA installed (2021.6.2), and been using the Mazda component for some time. Lately - 2-3 days now - the component stopped working and it's stating: "Retrying setup: Request failed: An update to Mazda app is required to continue"
```
Logger: homeassistant.components.mazda
Source: components/mazda/__init__.py:43
Integration: Mazda Connected Services (documentation, issues)
First occurred: 7:27:21 AM (318 occurrences)
Last logged: 2:47:51 PM
Unknown error occurred during Mazda update request: Request failed: An update to Mazda app is required to continue

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 142, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 43, in with_timeout
    return await task
  File "/usr/local/lib/python3.8/site-packages/pymazda/client.py", line 22, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
  File "/usr/local/lib/python3.8/site-packages/pymazda/controller.py", line 21, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 154, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 169, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 241, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
pymazda.exceptions.MazdaException: Request failed: An update to Mazda app is required to continue
``` 
I tried to delete the component and re-add it. On the Android phone it shows the info/details, but in HA there is no data available. 

Thank you.

**Comment by Mr-Grover** [comment]
That is more or less the same issue I am having. Thanks for sharing !

**Comment by bdr99** [comment]
It looks like there has been a change on the Mazda API side. Oddly, I'm in North America and the integration is still working fine for me, so I think this change is specific to the Europe region. I'll look into it and see if I can figure out what changed.

**Comment by pr0fetul** [comment]
Thank you for your time and dedication. 
If I can help with anything, please do not hesitate to ask. 

Thank you

**Comment by bdr99** [comment]
I think I found the problem. I just had to increment the app version number from 7.2.0 to 7.3.0 which is the newest version. I just created a new branch in this repo called `app-version-730` that contains the fix. @Mr-Grover @pr0fetul would one of you be able to try this branch and see if you are able to connect and interact with your car?

**Comment by pr0fetul** [comment]
Hi @bdr99 , thank you for the fast reply. As I am trying to run the code, using the new branch change, when I run the code in PyCharm (Python 3.6), the loop does not seem to finish. Here is the code I am running:
```
user = "email"
password = "pass"

import asyncio
import pymazda



async def test() -> None:
    # Initialize API client (MNAO = North America)
    client = pymazda.Client(user, password, "MME")

    # Get list of vehicles from the API (returns a list)
    vehicles = await client.get_vehicles()

    # Loop through the registered vehicles
    for vehicle in vehicles:
        # Get vehicle ID (you will need this in order to perform any other actions with the vehicle)
        vehicle_id = vehicle["id"]

        # Get and output vehicle status
        status = await client.get_vehicle_status(vehicle_id)
        print(status)

        # Start engine
        #await client.start_engine(vehicle_id)

    # Close the session
    await client.close()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())
```
I let it run for 5 min - but no return unfortunately. In my C:\Python36\Lib\site-packages\pymazda I changed the file connection.py to the one posted in your branch with the updated version and then re-done the import to make sure that the file used is the correct one. 
Am I doing it wrong?

**Comment by AllPurposeBen** [comment]
Possibly related, maybe not and should be broken to a new issue but I'm getting a failure in HA as well, also in my own wrapper script for local command line use. 

I'm seeing timeouts, not the same errors as above, and I'm in the US region. I logged into the account I use for this in the app and confirmed it's not locked or anything nerfing the account.

<details>
  <summary>In HA, I get this error:</summary>
  
```
Logger: homeassistant.components.mazda
Source: components/mazda/__init__.py:43 
Integration: Mazda Connected Services (documentation, issues) 
First occurred: 9:54:16 AM (157 occurrences) 
Last logged: 11:50:09 AM

Unknown error occurred during Mazda update request:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 43, in with_timeout
    return await task
  File "/usr/local/lib/python3.8/site-packages/pymazda/client.py", line 22, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
  File "/usr/local/lib/python3.8/site-packages/pymazda/controller.py", line 21, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 154, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 169, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.8/site-packages/pymazda/connection.py", line 223, in __send_api_request
    response = await self._session.request(method, self.base_url + uri, headers=headers, data=encrypted_body_Str)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 142, in async_update_data
    vehicles = await with_timeout(mazda_client.get_vehicles())
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 43, in with_timeout
    return await task
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```
</details>

<details>
  <summary>In my own script running on just my laptop trying to `client.get_vehicles()`, I get this:</summary>

  ```
Traceback (most recent call last):
  File "/Users/benny/git/mazda-api-tool/mazda_api_tool.py", line 183, in <module>
    run_output = loop.run_until_complete(main_job())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/benny/git/mazda-api-tool/mazda_api_tool.py", line 99, in main_job
    await output_all_data()
  File "/Users/benny/git/mazda-api-tool/mazda_api_tool.py", line 42, in output_all_data
    vehicles = await client.get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/pymazda/client.py", line 22, in get_vehicles
    vec_base_infos_response = await self.controller.get_vec_base_infos()
  File "/usr/local/lib/python3.9/site-packages/pymazda/controller.py", line 21, in get_vec_base_infos
    return await self.connection.api_request("POST", "remoteServices/getVecBaseInfos/v4", body_dict={"internaluserid": "__INTERNAL_ID__"}, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 154, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 169, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 223, in __send_api_request
    response = await self._session.request(method, self.base_url + uri, headers=headers, data=encrypted_body_Str)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10ce26c40>
```
</details>

**Comment by bdr99** [comment]
@AllPurposeBen thanks for the info. It looks like Mazda just made another change to their API last night, which broke this library. This is in addition to the change that caused the original issue reported by @Mr-Grover. I'm working on determining the best course of action and will post an update here when I figure anything out.

**Comment by pr0fetul** [comment]
It's similar with what I am getting above. It might be that they changed the auth method and it's not responding correctly, or they have introduced a new check during the auth/retrieval of data.... my 2 cents.

**Comment by bdr99** [comment]
As an update, I figured out that the timeout issue is caused by the `X-acf-sensor data` HTTP header. `pymazda` currently leaves this header blank as you can see here:

https://github.com/bdr99/pymazda/blob/ceac6d7402c5e08227c2875f176c717001f71ebb/pymazda/connection.py#L203-L214

This worked fine for several months, but Mazda is now validating this header and will not accept an invalid value. I tried using a value captured from the app on my phone, and it worked for a few hours, but eventually stopped working (presumably because it contains a timestamp). The challenge will be to figure out how the app generates this value, and implement the same logic in the python code.

**Comment by Mr-Grover** [comment]
Thanks for digging into this. Doesn't seem like an easy fix :(

**Comment by bdr99** [comment]
> 
> 
> Thanks for digging into this. Doesn't seem like an easy fix :(

Yes, unfortunately I think it's going to be rather difficult. I need to understand the structure of the `X-acf-sensor-data` header and determine how to generate a value that the API will accept. I've made some progress toward this goal but I still have a lot more work to do.

**Comment by pr0fetul** [comment]
Hi @bdr99 ,
Any updates for this integration? Can I help with something maybe? 

Thank you very much for your work.

**Comment by bdr99** [comment]
Progress has been good so far. It was an extremely complex process that took me several weeks to understand, but I'm now able to semi-reliably generate valid values for the `X-acf-sensor-data` header. There are still a few more issues to work out. I'll probably need to increase the polling interval and add some caching, since the API seems to be more sensitive to excessive requests now. Also, my current code is written in TypeScript for [node-mymazda](https://github.com/bdr99/node-mymazda), the Node.js version of this library, so I still need to convert it to Python. With that said, I hope to have a test version of the HA integration available within the next week or two 🙂

**Comment by pmiguelcruz** [comment]
Sign me up for testing (North America here) @bdr99

**Comment by bdr99** [comment]
I have a fixed version of `pymazda` ready for testing! So far it has been working perfectly for me, but I need to test it for a couple of days to be certain that it's really working. It's great to see my car entities working again on my HA dashboard 🙂
![image](https://user-images.githubusercontent.com/2292715/124867124-7fa68600-df8b-11eb-898f-816b0b8b6aa1.png)

I'd appreciate it if some of you could test it as well. @Mr-Grover @pr0fetul @AllPurposeBen @pmiguelcruz 

If you want to test `pymazda` directly, just checkout the `sensor_data` branch of this repo.

If you want to test the Home Assistant integration, please follow these steps:
1. If it doesn't already exist, create a `custom_components` folder in your Home Assistant config folder (folder that contains `configuration.yaml`)
2. Download this file: [mazda_sensor_data_test.zip](https://github.com/bdr99/pymazda/files/6781746/mazda_sensor_data_test.zip)
3. Extract the "mazda" folder from the zip archive into your `custom_components` folder
4. Restart Home Assistant
5. If you already have the Mazda integration set up, it should start working. If not, you can add it via Configuration -> Integrations -> Add Integration.
6. Don't forget to delete the "mazda" folder when you are finished testing, to revert back to the Mazda integration that is built into HA

I had to make a few small compromises to avoid issues with rate limiting. I reduced the update interval from 1 minute to 3 minutes. I also added caching for the vehicle list. This means if you add a new vehicle to your account or rename a vehicle, you won't see those changes reflected in HA until you reload the integration or restart HA. I think these minor sacrifices are worth it to hopefully get the integration working reliably.

Please let me know if it works or if you have any issues! If you encounter issues, please add the following to your `configuration.yaml` to enable debug logging for `pymazda`:
```yaml
logger:
  default: warn
  logs:
    pymazda: debug
```
After that, restart Home Assistant and replicate the issue. Then please share your logs here so I can diagnose the issue.

**Comment by pr0fetul** [comment]
Hi @bdr99 , good morning. I have used the files posted above, and as I already had the Mazda integration setup, it picked it up and started working. 
Now it seems to work as previously. No errors thrown. The only thing (but I think this is probably because of the region - Romania - EU) is that tire pressure and car details are not fully displayed. Also, although I tried using some scripts with the functionalities the code provides, I cannot remotely start/stop the car or turn on/off hazard lights. 

![image](https://user-images.githubusercontent.com/17175289/124877519-d46def00-dfd3-11eb-82a0-e8b7e9069a5e.png)

![image](https://user-images.githubusercontent.com/17175289/124877574-e354a180-dfd3-11eb-9b0c-c732c4b8c294.png)

**Comment by bdr99** [comment]
@pr0fetul Thanks for testing! Tire pressure and fuel distance being unknown is normal for CX-5.

You mentioned that you can't start/stop the car or turn on/off the hazard lights. Did you try this from in HA? Was there any log output when you tried?

**Comment by pr0fetul** [comment]
Hi, also, the start/stop I think it's dependent on the country maybe. Here is the error output:
```
Logger: homeassistant
Source: custom_components/mazda/__init__.py:107
Integration: Mazda Connected Services
First occurred: 11:05:20 AM (1 occurrences)
Last logged: 11:05:20 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/mazda/__init__.py", line 105, in async_handle_service_call
    await api_method(vehicle_id)
  File "/usr/local/lib/python3.9/site-packages/pymazda/client.py", line 153, in turn_on_hazard_lights
    await self.controller.light_on(vehicle_id)
  File "/usr/local/lib/python3.9/site-packages/pymazda/controller.py", line 85, in light_on
    response = await self.connection.api_request("POST", "remoteServices/lightOn/v4", body_dict=post_body, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 158, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 173, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 245, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
pymazda.exceptions.MazdaException: Request failed: **Verifică datele introduse și încearcă din nou.**  (400C03) #Check for data input and try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 404, in _async_run
    return await self.script.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/mazda/__init__.py", line 107, in async_handle_service_call
    raise HomeAssistantError(ex) from ex
homeassistant.exceptions.HomeAssistantError: Request failed: **Verifică datele introduse și încearcă din nou.**  (400C03) #Check for data input and try again
```

**Comment by bdr99** [comment]
@pr0fetul Were you able to start/stop the vehicle before the HA integration stopped working? Also, are you able to start/stop it from the MyMazda app?

**Comment by Mr-Grover** [comment]
Great news :) Hopefully I can test later today

**Comment by pr0fetul** [comment]
No, that's what I was saying - maybe in US it works, but here in EU I think that both the app (MyMazda) and the car are not configured to remote start/stop / unlock or turn on/off hazard lights. I personally think it's stupid, but ... it's for Mazda to decide and implement first, so we can benefit afterwards. 
Anyway - thank you very much for your hard work - I can confirm that all the options that were previously available (to me) are now present as well... too bad for the other remote options ...

**Comment by bdr99** [comment]
@pr0fetul OK great! Yes, it's unfortunate that Mazda restricts those features in your region. But I'm glad to hear that the functionality is the same as it was before. Thanks again for the testing!

**Comment by Valdorama** [comment]
So the 'fuel remaining' and tire pressure is not available at all for CX5s, or is it only intermittently reported by the API? Had visions of Home Assistant blasting notifications everywhere when the fuel dropped below a threshold. 

Great work by the way, appreciate the effort you've put into this.

**Comment by bdr99** [comment]
@Valdorama "Fuel remaining" is available, but "fuel distance remaining" is not available. Fuel remaining is the percentage of fuel, but fuel distance remaining is the estimated distance the car can drive before the fuel runs out.

**Comment by AllPurposeBen** [comment]
Seems to be working for me, I see entities for tire pressure, fuel, lock and location. 

I don't see services listed for send_poi or start/stop engine but that may just be me needing to configure something in HA I'm missing. They are available and working from the Developer Tools menu.

**Comment by bdr99** [comment]
@AllPurposeBen Thanks! Where specifically are you not seeing the services?

**Comment by AllPurposeBen** [comment]
If I look at the car in the Configuration -> Devices screen or if I look at tile for the integration in Configuration -> Integration.

**Comment by bdr99** [comment]
@AllPurposeBen Ah, ok. That is normal. Typically, to use those services, you would add them to an automation or script. You should see them in the services list when adding a "Call service" action to an automation.

**Comment by AllPurposeBen** [comment]
I was thinking I was missing a convention in how to do it, make a script, attach button to it. I see now where I was missing switching the action type in the script builder to services. Cool, thank you!

**Comment by Mr-Grover** [comment]
My computer is acting up so I won’t be able to test. Sounds like it’s working anyway.

**Comment by bdr99** [comment]
Thanks everyone for the testing. I just released this fix as version 0.2.0 of `pymazda`. I also submitted a PR (https://github.com/home-assistant/core/pull/52775) to get this fix added to Home Assistant. Hopefully they can get it included in one of the patch releases for July.

**Comment by pmiguelcruz** [comment]
It works perfectly on my side.

Thanks for working on this Brandon!
Hopefully it gets included in one of the next releases of HA.


— Pedro

**Comment by bdr99** [comment]
@pmiguelcruz Glad to hear it! It looks like the fix is scheduled to be included in HA 2021.7.2 which should be released in the next couple of days.

**Comment by AllPurposeBen** [comment]
I didn't notice this before because it takes several days to manifest but twice since I installed this branch, the integration broke because it seems to have forgotten the password for the MazdaConnect account I'm using. As soon as I re-enter it, it works fine.

I can't reproduce on demand, rebooting the host or restarting HA doesn't trigger it. Not sure if it's the integration or HA itself.

I'm on core-2021.7.1.

**Comment by bdr99** [comment]
@Mr-Grover @pr0fetul @AllPurposeBen @pmiguelcruz Home Assistant 2021.7.2 was just released, and it includes the fix for this issue. If you were using the test version of the integration, make sure you delete it from your `custom_components` folder before upgrading.


> I didn't notice this before because it takes several days to manifest but twice since I installed this branch, the integration broke because it seems to have forgotten the password for the MazdaConnect account I'm using. As soon as I re-enter it, it works fine.
> 
> I can't reproduce on demand, rebooting the host or restarting HA doesn't trigger it. Not sure if it's the integration or HA itself.
> 
> I'm on core-2021.7.1.

@AllPurposeBen That's strange, I haven't seen that problem before. I don't think it's related to this issue. If it continues after removing the test version from `custom_components` and upgrading to 2021.7.2, then can you please open a separate issue report for this?
