### ISSUE TITLE
Support for long-term statistics in Home Assistant

### ISSUE THREAD

**Issue by Valdorama** [bdr99/pymazda#18]
Hi - not sure if this is the right mechanism to raise such an enhancement request, given that this is the project for the MCS python API and not directly related to Home Assistant. 

I have create a new [feature request](https://community.home-assistant.io/t/mazda-connected-services-integration-support-for-long-term-statistics/378922) on the HA community site, to have support for [long-term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics) added to the MCS HA integration. 

I believe that doing so requires that a new sensor property - state_class - be implemented.

Would be cool to track/graph vehicle usage over the long term.

**Comment by bdr99** [comment]
Hi @Valdorama. Good news: I added the `state_class` attribute to the sensor entities in the HA integration. It will be included in 2022.2. Enjoy!

**Comment by Valdorama** [comment]
Wonderful, thank you!
