### ISSUE TITLE
Feature request - add sensors for doors and windows

### ISSUE THREAD

**Issue by pr0fetul** [bdr99/pymazda#21]
Hi Brandon, 

I don't know if this is on your to-do list, but can we have some sensors defined in HA based on the output from services? 
The new diagnostic log shows the results are there, can you please help add these values under sensors in HA?
Here is an output from my car:
```
"data": {
      "vin": "**REDACTED**",
      "id": "**REDACTED**",
      "nickname": "CX5",
      "carlineCode": "MAZDA CX-5",
      "carlineName": "Mazda CX-5",
      "modelYear": "0000",
      "modelCode": "KJP8",
      "modelName": "Mazda CX-5",
      "automaticTransmission": false,
      "interiorColorCode": "KF2",
      "interiorColorName": "Tapi\u021berie piele Nappa maro, scaune fa\u021b\u0103-spate \u00eenc\u0103lzite, scaune fa\u021b\u0103 ventilate",
      "exteriorColorCode": "45B",
      "exteriorColorName": "Albastru Eternal",
      "isElectric": false,
      "status": {
        "lastUpdatedTimestamp": "20220211115200",
        "latitude": "**REDACTED**",
        "longitude": "**REDACTED**",
        "positionTimestamp": "20220211114645",
        "fuelRemainingPercent": 81.0,
        "fuelDistanceRemainingKm": null,
        "odometerKm": 6396.9,
        "doors": {
          "driverDoorOpen": false,
          "passengerDoorOpen": false,
          "rearLeftDoorOpen": false,
          "rearRightDoorOpen": false,
          "trunkOpen": false,
          "hoodOpen": false,
          "fuelLidOpen": true
        },
        "doorLocks": {
          "driverDoorUnlocked": false,
          "passengerDoorUnlocked": false,
          "rearLeftDoorUnlocked": false,
          "rearRightDoorUnlocked": false
        },
        "windows": {
          "driverWindowOpen": false,
          "passengerWindowOpen": false,
          "rearLeftWindowOpen": false,
          "rearRightWindowOpen": false
```
false for Closed / true for Open type of conversion? 

Also, just asking, have you tried to switch the region area - to see if more options become available/unavailable ? :)  like a method of circumventing the restrictions from the API?

**Comment by bdr99** [comment]
Hi @pr0fetul,
I have actually already been working on this. I submitted a PR here: https://github.com/home-assistant/core/pull/64604 and am currently waiting for review from the HA core team.

There will be binary sensor entities for the doors, trunk and hood. Also "plugged in" and "charging" status for electric vehicles. Unfortunately, the window status returned by the Mazda API doesn't seem to be correct. It is always `false` even if the windows are actually open. I don't think there is anything we can do about this. So, I didn't add binary sensors for the windows. I might also remove them from pymazda to avoid confusion.

I have tried logging in via a different region. Unfortunately the accounts are region-specific. You can only log into an account via the region it was originally created in.

**Comment by bdr99** [comment]
Binary sensors for doors will be added in Home Assistant 2022.4.

As stated above, binary sensors for windows are unfortunately not possible.
