### ISSUE TITLE
pymazda and M1 CPU

### ISSUE THREAD

**Issue by CacioGit** [bdr99/pymazda#24]
I am having an issue getting pymazda working correctly on M1-based machines, and I am not sure if I am doing something incorrectly, or if the issue may be related to the M1 CPU.
I have this working correctly on two older Intel-based laptops..

What I see is that the script seems to get stuck at the main loop "loop.run_until_complete(test())":
---
python3 mazda.orig.py 
^CTraceback (most recent call last):
  File "mazda.orig.py", line 30, in <module>
    loop.run_until_complete(test())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
---

A "pip3 install -U pymazda" shows everything being updated correctly to the current 0.3.6 release

Any debugging suggestions for me to look into?
TIA

**Comment by bdr99** [comment]
Hi @CacioGit,

To start, can you add the following to your code, before the first call to pymazda? This should provide some debugging output that may be helpful.
```python
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by CacioGit** [comment]
This is what I call a fast answer @bdr99 :)

Seems to be stuck at the "Sending POST request" step:
--
DEBUG:asyncio:Using selector: KqueueSelector
INFO:pymazda.connection:Retrieving encryption keys
DEBUG:pymazda.connection:Sending POST request to service/checkVersion
INFO:pymazda.connection:Successfully retrieved encryption keys
INFO:pymazda.connection:No access token present. Logging in.
INFO:pymazda.connection:Logging in as myaccount@myaccount.com
INFO:pymazda.connection:Retrieving public key to encrypt password
INFO:pymazda.connection:Sending login request
INFO:pymazda.connection:Successfully logged in as myaccount@myaccount.com
DEBUG:pymazda.connection:Sending POST request to remoteServices/getVecBaseInfos/v4
---

On my Intel-machine, I see the following answer coming in:
---
..
INFO:pymazda.connection:Successfully logged in as myaccount@myaccount.com
DEBUG:pymazda.connection:Sending POST request to remoteServices/getVecBaseInfos/v4
DEBUG:pymazda.connection:Response payload: {'resultCode': '200S00', 'vecBaseInfos': [{'Vehicle': {'rsaSupport': 1,...
---

I tried turning off the MacOS firewall just in case.. didn't make a difference.
Should I look into capturing a Wireshark trace, or does this give you an idea of what may be happening, from your previous experiences?

**Comment by bdr99** [comment]
Hmm, that's what I was afraid of...

I think the Mazda API is actually using a [TLS Fingerprinting](https://stormwall.network/knowledge-base/termin/tls-fingerprinting) technique to attempt to block automated requests. It works by inspecting the parameters of the TLS handshake such as supported ciphers, TLS extensions, etc, and using that to guess which type of client is sending the request. If Mazda determines that the TLS handshake is likely to have originated from an automated system such as Python, they just let the request time out as you have seen. I only started noticing this recently, and it only happens on some of my devices, even though they are running the exact same Python code. I think there are differences in the way Python executes the TLS handshake, based on factors such as OS, Python version, and the versions of system libraries like OpenSSL, which could explain why it only happens on certain devices.

I actually just recently spent several days trying to find a solution to this issue, but came up mostly empty handed. In my research, I found that Python doesn't give much control over the specifics of the TLS handshake. In https://github.com/bdr99/pymazda/commit/c76c310f39303458d361a1f92d320aec4d2b3b64 I changed the list of TLS ciphers, which is one of the things that Python does allow you to customize, and it seemed to help a bit on some of my systems. But as you have seen, even with that change, there are still some devices that perform the handshake in a way that causes Mazda to block the request. If you have any ideas, I'd love to hear them, but at this point I'm afraid there might not be much that we can do.

**Comment by CacioGit** [comment]
I did try collecting a "tcpdump" trace, but I can't really spot anything "obvious" in it..
I will try collecting one from the older Mac and one from this one and see if anything stands out.

If the issue is indeed with a "fingerprinting" approach in trying to keep non-official-apps out of their servers, it may only be the beginning of a cat-and-mouse game then, pity..

I will try installing pyMazda in a docker container as well, and see if I can use that "workaround" to get the script working on my new machine.

I will keep you updated on the tcpdump too, but may take a few days / next weekend.

I really appreciate your assistance!

**Comment by bdr99** [comment]
Thanks! Yeah, it does seem like it's going to be a cat-and-mouse game unfortunately. Let me know if you're able to figure anything out.

By the way, I also tried the Docker approach. I had some luck with the `python:3.10-alpine` image.

**Comment by bdr99** [comment]
Also, I'm not sure if you are aware but I also maintain a Node.js version of this library called `node-mymazda`. So far it doesn't seem to be affected by this issue.

**Comment by CacioGit** [comment]
I am going to Close the log:
I switched to using the Node.js version, as I didn't like the idea of having a container running just as a workaround to the fingerprinting issue with this Python module.

It took me a while to get all the pieces together for the Node.js solution, but in the end I could integrate it with my own tool quite nicely.

Thank you for having looked into this issue, and even more for having both a Python and a Node.Js version 👍
