### ISSUE TITLE
New version of Mazda app again?

### ISSUE THREAD

**Issue by teha36** [bdr99/pymazda#27]
Looks like we have a new version on the Mazda app again since yesterday
I see the following in my HA integration
Request failed: An update to Mazda app is required to continue;

**Comment by bdr99** [comment]
Which version of HA are you using?

**Comment by teha36** [comment]
Sorry to bother you, I missed the 2023.3.5 update and was still on the 2023.3.1
All is working fine after upgrade, thank you
