### ISSUE TITLE
MX-30 Feature set

### ISSUE THREAD

**Issue by Mr-Grover** [bdr99/pymazda#3]
Hello,

The mx-30 supports extra features not seen in other Mazda's. Let me know if you can add it and I would be happy to test :)

**Comment by bdr99** [comment]
Thanks for the offer to help! I would love to add support for these extra features, but I will definitely need your help for testing, since I don't have an MX-30.

What are the extra features that the MX-30 supports? Also, do the current features work correctly with your MX-30?

**Comment by Mr-Grover** [comment]
Here is the quick break down from Mazda. And yes the current service works it even pulls in the range !(thinks it fuel hehe) Thanks so much for your hard work. Happy to test and help where I can

I would say the stand out features are Door lock status and locking the door(you can't unlock) Viewing and controlling the AC

```
As an owner of a All-New Mazda MX-30, you'll get the most out of the new MyMazda App features.
Enjoy numerous remote control functions, e.g. for air-conditioning, start/stop charging and lock your vehicle
Check the status of your Mazda MX-30 remotely and control the driving range, tyre pressure and required time for charging
```

**Comment by bdr99** [comment]
Glad to hear the library is working with your car. Actually `pymazda` already has support for door lock status and locking and unlocking doors. It wasn't documented very well, but I just updated the readme to hopefully make things a lot more clear.

The door lock status is included in the `client.get_vehicle_status()` response, and the doors can be locked or unlocked with `client.lock_doors()` and `client.unlock_doors()`. Let me know if these are working for you.

As for controlling the AC and starting/stopping charging, I will have to look into those. My car doesn't have these features but I'll see if I can figure it out by examining the app.

**Comment by Mr-Grover** [comment]
Thanks for that. I will poke around when I get some time.

**Comment by Mr-Grover** [comment]
Just tested `await client.lock_doors(vehicle_id)`. Looks to be working fine for me. The status on the other hand was always False not sure why that was.

**Comment by bdr99** [comment]
@Mr-Grover Thanks for testing `lock_doors`. As for the status, I think it may just take some time to update. Everything is slow since the car is communicating over a mobile network.

I just created a test implementation of the `start_charging` and `stop_charging` methods. I have no idea if they work, Mazda doesn't even sell any EVs in my country. Would you be able to test them with your car? The code is pushed to the [`charge`](https://github.com/bdr99/pymazda/tree/charge) branch in this repo.

**Comment by Mr-Grover** [comment]
Yes I think you’re right and I been meaning to test it again. Even the official Mazda app takes a few mins to alert me. 

I will test those features when I get some time. I haven’t even used the MyMazda app to stop or start the charge so this will be a new one for me haha

**Comment by Mr-Grover** [comment]
So sorry for the delay ! but I was able to finally test the stop and start charge commands. Both worked for me without issue YAY :)

Also you were right about the door status I tested again and it did in fact switch from false to true after about a min or two.

There is nothing I see from the get vehicle status method to show that the car is charging or not just a FYI.

Do you think we can get the door status and lock door feature set added to the version pulled from HA integrations ? Along with the stop/charge for Mazda EV owners ? 

Writing automation to lock the car door would be great ! Thanks again for doing all the hard work !

**Comment by bdr99** [comment]
Home Assistant 2021.6 was released last week which includes support for locking/unlocking the doors, and adds services such as starting/stopping the engine, starting/stopping charging, flashing the lights, etc. Enjoy!

**Comment by Mr-Grover** [comment]
Yes I did see that ! Thanks so much. Will update this weekend. Ever since HA moved to a monthly cycle I been week behind because of my 2 week upgrade cycle haha. Will keep you posted

**Comment by bdr99** [comment]
Hi @Mr-Grover, I'm going to close this issue now, since the start/stop charging and door lock features are now added to the HA integration. If you have any problems with those features then please feel free to open a new issue.
