### ISSUE TITLE
HA Integration throwing error `Request failed: An update to Mazda app is required to continue`

### ISSUE THREAD

**Issue by rachit-aggarwal** [bdr99/pymazda#31]
Hi,

For the past two days, the Mazda buttons were grayed out on the HA dashboard and today when I looked into integrations, I noticed the error `Retrying setup: Request failed: An update to Mazda app is required to continue`. Seems like this a repeat issue where the API at the source side was updated.

I just wanted to bring to your attention and see if there any issue at my end.

**Comment by bdr99** [comment]
Hi, this should be fixed in HA 2023.7.0. Can you try updating and see if it fixes it for you?

**Comment by rachit-aggarwal** [comment]
Apologies, I missed the core issue list. Just updated and it fixed it. Thanks!
