### ISSUE TITLE
Alternatives to pycryptodome

### ISSUE THREAD

**Issue by AllPurposeBen** [bdr99/pymazda#7]
This may be a big ask but is there a pure python alternative to pycrpytodome that could be used without too much hassle? 

I'd like to be able to call this module from PyPi on iOS but because of the sandboxing within iOS,[ it can't really run anything with c extensions](https://pyto.readthedocs.io/en/latest/). Here's a [list on the pre-installed/rigged-to-work packages Pyto has](https://pyto.readthedocs.io/en/latest/third_party.html) and it can install other things from pyPI that are pure python.

If that would be a big undertaking, I totally understand and I could alternatively try doing the same task in Scriptable on iOS using js or just throw all this into a lambda function and webhook it.

**Comment by bdr99** [comment]
Hmm, I could probably get it to work using [cryptography](https://pypi.org/project/cryptography/). This should work on iOS, since it's on the list from your link, right?

I think this would be a good change to make anyway, since cryptography seems a bit more modern and robust than pycryptodome.

**Comment by AllPurposeBen** [comment]
Yep, cryptography imports without complaint. Thanks!

**Comment by bdr99** [comment]
Well, that was easy! It didn't take long at all to convert the library from pycryptodome to cryptography. Here's the commit: https://github.com/bdr99/pymazda/commit/3e5eff5e2a556ae62a528b74e3a88dc604177f7f

I hope this helps with what you're trying to do on iOS! It was a good change anyway, I like this new library much better.
